class CardData
{
    static getNewCard()
    {
        return CardData.data.slice(0);
    }
}

CardData.data = [{iconPos: 'j1.jpg', type: '0', val: 17},
    {iconPos: 'j2.jpg', type: '0', val: 16},
    {iconPos: 't1.jpg', type: '1', val: 14},
    {iconPos: 't2.jpg', type: '1', val: 15},
    {iconPos: 't3.jpg', type: '1', val: 3},
    {iconPos: 't4.jpg', type: '1', val: 4},
    {iconPos: 't5.jpg', type: '1', val: 5},
    {iconPos: 't6.jpg', type: '1', val: 6},
    {iconPos: 't7.jpg', type: '1', val: 7},
    {iconPos: 't8.jpg', type: '1', val: 8},
    {iconPos: 't9.jpg', type: '1', val: 9},
    {iconPos: 't10.jpg', type: '1', val: 10},
    {iconPos: 't11.jpg', type: '1', val: 11},
    {iconPos: 't12.jpg', type: '1', val: 12},
    {iconPos: 't13.jpg', type: '1', val: 13},
    {iconPos: 'x1.jpg', type: '2', val: 14},
    {iconPos: 'x2.jpg', type: '2', val: 15},
    {iconPos: 'x3.jpg', type: '2', val: 3},
    {iconPos: 'x4.jpg', type: '2', val: 4},
    {iconPos: 'x5.jpg', type: '2', val: 5},
    {iconPos: 'x6.jpg', type: '2', val: 6},
    {iconPos: 'x7.jpg', type: '2', val: 7},
    {iconPos: 'x8.jpg', type: '2', val: 8},
    {iconPos: 'x9.jpg', type: '2', val: 9},
    {iconPos: 'x10.jpg', type: '2', val: 10},
    {iconPos: 'x11.jpg', type: '2', val: 11},
    {iconPos: 'x12.jpg', type: '2', val: 12},
    {iconPos: 'x13.jpg', type: '2', val: 13},
    {iconPos: 'h1.jpg', type: '3', val: 14},
    {iconPos: 'h2.jpg', type: '3', val: 15},
    {iconPos: 'h3.jpg', type: '3', val: 3},
    {iconPos: 'h4.jpg', type: '3', val: 4},
    {iconPos: 'h5.jpg', type: '3', val: 5},
    {iconPos: 'h6.jpg', type: '3', val: 6},
    {iconPos: 'h7.jpg', type: '3', val: 7},
    {iconPos: 'h8.jpg', type: '3', val: 8},
    {iconPos: 'h9.jpg', type: '3', val: 9},
    {iconPos: 'h10.jpg', type: '3', val: 10},
    {iconPos: 'h11.jpg', type: '3', val: 11},
    {iconPos: 'h12.jpg', type: '3', val: 12},
    {iconPos: 'h13.jpg', type: '3', val: 13},
    {iconPos: 'k1.jpg', type: '4', val: 14},
    {iconPos: 'k2.jpg', type: '4', val: 15},
    {iconPos: 'k3.jpg', type: '4', val: 3},
    {iconPos: 'k4.jpg', type: '4', val: 4},
    {iconPos: 'k5.jpg', type: '4', val: 5},
    {iconPos: 'k6.jpg', type: '4', val: 6},
    {iconPos: 'k7.jpg', type: '4', val: 7},
    {iconPos: 'k8.jpg', type: '4', val: 8},
    {iconPos: 'k9.jpg', type: '4', val: 9},
    {iconPos: 'k10.jpg', type: '4', val: 10},
    {iconPos: 'k11.jpg', type: '4', val: 11},
    {iconPos: 'k12.jpg', type: '4', val: 12},
    {iconPos: 'k13.jpg', type: '4', val: 13}];

    export default CardData;